trigger:
 paths:
   include:
     - project/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7e246359-08e7-4fad-9e25-1ac883f583d5'
  imageRepository: 'my-ansible-demo'
  containerRegistry: 'index.docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/project/playbooks/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: Default


stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'project/playbooks/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push 
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
- stage: Update
  displayName: Update 
  jobs:
  - job: Update
    displayName: Update
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: 'script/imageUpdate.sh'
        args: '$(imageRepository) $(tag)'